- .ci.yml
- .travis.yml
- doc/dev/README.md
Remove dotCI config, and add a travis config. Make some small changes to the README
Some notes on the travis config:
1) Force an update of the Oracle JDK - the default one is 1.8.31 which has some bugs which causes the JVM to segfault while running Monsoon's tests.
2) While the tests run in Travis' Java environment, node/npm is available. Ensure that node and npm are updated before running the tests for the UI (the default version is too old to install Angular 2)
3) `sudo: required` forces the tests to be run inside a VM inside of a Docker container. The VM has more memory, which is necessary to run the tests for the history module.
Future work:
Optimize the history module tests to run within 4GB of memory.
Sample passing builds:
https://travis-ci.org/dmjb/monsoon/builds/141826559
> use travis-ci for continuous integration

- api_server/src/main/frontend/package.json
Since whenever it moves it requires a complete upgrade of everything angular.
This unbreaks my build.
> Lock down angular2-modal version.

- impl/src/main/java/com/groupon/lex/metrics/MetricRegistryInstance.java
- impl/src/test/java/com/groupon/lex/metrics/JmxClient_remoteTest.java
- intf/src/main/java/com/groupon/lex/metrics/httpd/AlreadyStartedException.java
- lib/src/main/java/com/groupon/lex/metrics/lib/BufferedIterator.java
Catching `Throwable` is A Bad Thing™ as it can potentially catch non recoverable JVM errors. There is one place in the code where it is necessary to accept a `Throwable` argument, other than that - replace all occurrences of `Throwable` with `Exception`.
Catching the blanket `Exception` isn't a great idea within of itself, but this is a start :)
> remove unnecessary catches of Throwable

- api_server/src/main/java/com/groupon/lex/metrics/api/ApiServer.java
- impl/pom.xml
- impl/src/main/java/com/groupon/lex/metrics/MetricRegistryInstance.java
- impl/src/main/java/com/groupon/lex/metrics/PipelineBuilder.java
- impl/src/main/java/com/groupon/lex/metrics/PushMetricRegistryInstance.java
- impl/src/main/java/com/groupon/lex/metrics/PushProcessorPipeline.java
- impl/src/main/java/com/groupon/lex/metrics/config/Configuration.java
- impl/src/test/java/com/groupon/lex/metrics/MetricRegistryInstanceTest.java
- impl/src/test/java/com/groupon/lex/metrics/PushProcessorPipelineTest.java
- impl/src/test/java/com/groupon/lex/metrics/config/ConfigurationTest.java
- impl/src/test/java/com/groupon/lex/metrics/config/parser/AbstractAlertTest.java
- impl/src/test/java/com/groupon/lex/metrics/config/parser/AbstractExpressionTest.java
- intf/src/main/java/com/groupon/lex/metrics/MetricRegistry.java
- intf/src/main/java/com/groupon/lex/metrics/PushProcessor.java
- intf/src/main/java/com/groupon/lex/metrics/Support.java
- prometheus/src/main/java/com/groupon/lex/prometheus/PrometheusServer.java
Create a pipeline type that encapsulates everything needed to run a push processor.  An added advantage is that we can now run with multiple processors.
While here, remove the String ``package_name`` from all constructors: it was used in the olden days to register JMX beans, but that isn't done anymore (in fact, accessing metrics via the JMX beans breaks push-based collectors, like *collectd*, which cleans out the set of metrics during a scrape).
This also implements a pipeline builder, to make it easy to create them and correctly start the pipeline.
Counterparts for pull-based collectors are not yet implemented.
> Push pipeline

- http_get_collector/src/main/java/com/groupon/lex/metrics/collector/httpget/UrlGetCollector.java
Bring timeouts for HTTP get collector in line with JMX collector:
both now abort after ~30 seconds.
> Make HTTP get collectors more lenient with slow servers.

- api_server/src/main/java/com/groupon/lex/metrics/api/MonsoonErrorHandler.java
Without logging them, they simply get lost forever.
> Log API endpoint exceptions.

- api_server/src/main/java/com/groupon/lex/metrics/api/ApiServer.java
- impl/src/main/java/com/groupon/lex/metrics/MetricRegistryInstance.java
- impl/src/main/java/com/groupon/lex/metrics/PipelineBuilder.java
- impl/src/main/java/com/groupon/lex/metrics/PushMetricRegistryInstance.java
- impl/src/main/java/com/groupon/lex/metrics/PushProcessorPipeline.java
- impl/src/main/java/com/groupon/lex/metrics/api/endpoints/ListMetrics.java
- impl/src/test/java/com/groupon/lex/metrics/PushProcessorPipelineTest.java
- intf/src/main/java/com/groupon/lex/metrics/PushProcessor.java
- Add explicit override for API.
- Create PipelineBuilder.build function that only takes a single supplier.
- Propagate failed collections to Push Processors, so they can decide how
trustworthy the data is.
This fixes some limitations I found while using the pipeline logic.
> Make pipeline and push processor interface more useful.

- .travis.yml
- history/src/test/java/com/groupon/lex/metrics/history/xdr/DirCollectHistoryTest.java
- history/src/test/java/com/groupon/lex/metrics/history/xdr/TSDataFileChainTest.java
- history/src/test/java/com/groupon/lex/metrics/history/xdr/support/FileSupport.java
- history/src/test/java/com/groupon/lex/metrics/history/xdr/support/StreamedCollection.java
- pom.xml
Make the history module use less memory.
- Use the name cache to reduce the number of GroupName/MetricName all over the place.
- Share width across Groups and Metrics, so the number of unique names is reduced.
- Abuse the reproducability property of the test-data, to replay the data rather than keep it all in RAM.
- Wrap the above inside a hackish (?) class that pretends to be both a stream and a collection.
- Use that class during equality comparisons, to compare large data sets without loading any of it into RAM at the same time.
Make the history module tests faster.
- Precalculate the collections of names, so that generation of test-data is faster.
- Tweaking the width and limit of the test data makes tests reach file roll-over sooner.
- Tweaking the max-size of the file makes tests …
> History less mem test

- history/src/main/java/com/groupon/lex/metrics/history/xdr/support/FileTimeSeriesCollection.java
- history/src/test/java/com/groupon/lex/metrics/history/xdr/support/FileTimeSeriesCollectionTest.java
- impl/src/main/java/com/groupon/lex/metrics/timeseries/AbstractTSCPair.java
- impl/src/main/java/com/groupon/lex/metrics/timeseries/BackRefTimeSeriesCollection.java
- impl/src/main/java/com/groupon/lex/metrics/timeseries/MutableTimeSeriesCollection.java
- impl/src/test/java/com/groupon/lex/metrics/timeseries/TimeSeriesCollectionPairInstanceTest.java
- intf/src/main/java/com/groupon/lex/metrics/timeseries/TimeSeriesCollection.java
- Instead of recreating the ``TimeSeriesValueSet`` each time, just expose the collection of values.
This means no useless copy of the TimeSeriesValue ``Map`` internal to both ``TimeSeriesValueSet`` and ``TimeSeriesCollection``.
> - Also create ``getTSValuesAsMap()``, which groups by SimpleGroupPath.
>   (Not sure I like that function, especially as the only useage is in a test.)
Actually, I decided that ``getTSValuesAsMap()`` was a stupid function and erased it.
> All calls to getTSValues() are followed by stream.

- impl/src/main/java/com/groupon/lex/metrics/history/HistoryContext.java
- impl/src/main/java/com/groupon/lex/metrics/timeseries/AbstractTSCPair.java
For some reason (streaming logic?) the history context would emit the same
context multiple times.  This probably is because the context was mutating
itself during iteration.  Make it immutable, so that any premature advancing
of the context won't cause it to emit the same context multiple times.
As an added bonus, this makes the history context concurrency-safe, i.e.
a stream that wants to parallellize evaluation will now be able to do so
correctly.
------------------------------------------------------------------------
My unconfirmed suspicion is that the stream does lazy evaluation of the
iterator return value.  Because ``/api/monsoon/eval`` uses a buffering
iterator for throughput, this means the context will have advanced
before the full evaluation of the metrics is complete. …
> Make history context immutable.

- impl/src/main/java/com/groupon/lex/metrics/MetricRegistryInstance.java
- impl/src/main/java/com/groupon/lex/metrics/PipelineBuilder.java
- impl/src/main/java/com/groupon/lex/metrics/PullMetricRegistryInstance.java
- impl/src/main/java/com/groupon/lex/metrics/PullProcessorPipeline.java
- impl/src/main/java/com/groupon/lex/metrics/PushMetricRegistryInstance.java
- impl/src/main/java/com/groupon/lex/metrics/config/Configuration.java
- impl/src/test/java/com/groupon/lex/metrics/MetricRegistryInstanceTest.java
- impl/src/test/java/com/groupon/lex/metrics/config/ConfigurationTest.java
- impl/src/test/java/com/groupon/lex/metrics/config/parser/AbstractAlertTest.java
- impl/src/test/java/com/groupon/lex/metrics/config/parser/AbstractExpressionTest.java
- prometheus/src/main/java/com/groupon/lex/prometheus/DisplayMetrics.java
- prometheus/src/main/java/com/groupon/lex/prometheus/PrometheusConfig.java
- prometheus/src/main/java/com/groupon/lex/prometheus/PrometheusMetrics.java
- prometheus/src/main/java/com/groupon/lex/prometheus/PrometheusServer.java
Implement a pipeline (okay, a ``PullMetricRegistryInstance``) for pull processors (like the prometheus processor.
- Moved rule-evaluation logic into the base ``MetricRegistryInstance``.
- ``Configuration.create(...)`` now takes a constructor argument, that allows the correct ``MetricRegistryInstance`` to be constructed.
- ``MetricRegistryInstance`` now takes care of the actual scrape, derived classes are responsible for the correct parameters only.
- ``PushMetricRegistryInstance`` is still stateful (no change there, except for how everything fits together).
- ``PullMetricRegistryInstance`` is stateless, but still protects *collectors* to ensure they don't get hit by re-entry considerations.
> Not sure if we should expose the entire ``PullMetricRegistryInstance``, as it has a lot of …
> Pull pipeline

- doc/rules/define.md
- impl/src/main/antlr4/imports/ConfigBnf.g4
- impl/src/main/java/com/groupon/lex/metrics/config/DerivedMetricStatement.java
- impl/src/main/java/com/groupon/lex/metrics/config/impl/DerivedMetricTransformerImpl.java
- impl/src/test/java/com/groupon/lex/metrics/config/parser/RuleTest.java
Allows defining tags during a define statement.
Example:
define my.group tag(instance = sample.metric app_name) {
cpu = sample.metric cpu;
mem = sample.metric mem;
}
> Define tags

- doc/config.md
- doc/expressions/name.md
- impl/src/main/antlr4/imports/ConfigBnf.g4
- impl/src/main/java/com/groupon/lex/metrics/timeseries/expression/NameExpression.java
- impl/src/test/java/com/groupon/lex/metrics/config/parser/FunctionTest.java
``name()`` takes a path name and converts it to a metric value.
Examples:
name(com.groupon.lex.monsoon) = "com.groupon.lex.monsoon"
name('17') = 17
name('true') = true
name('false') = false
This can be used in combination with match statement and the tagged-define (https://github.com/groupon/monsoon/pull/23) for instance:
match url.loaded.metrics body.instance.*.name as G, Name {
define ${G}.instance
tag (name = Name, instance = name(${Name[3]})) {
count = G ${M[:3]}.count;
}
}
> Implement name() function.

- impl/src/main/java/com/groupon/lex/metrics/config/JmxListenerMonitor.java
- impl/src/main/java/com/groupon/lex/metrics/resolver/CachingResolver.java
- impl/src/test/java/com/groupon/lex/metrics/config/JmxListenerMonitorTest.java
- intf/src/main/java/com/groupon/lex/metrics/ResolverGroupGenerator.java
- intf/src/main/java/com/groupon/lex/metrics/resolver/AsyncResolver.java
- intf/src/main/java/com/groupon/lex/metrics/resolver/NameBoundResolver.java
- intf/src/main/java/com/groupon/lex/metrics/resolver/NameBoundResolverSet.java
- intf/src/main/java/com/groupon/lex/metrics/resolver/Resolver.java
- intf/src/main/java/com/groupon/lex/metrics/resolver/SimpleBoundNameResolver.java
Create asynchronous resolver utilities.
Asynchronous resolvers:
- are refreshed after a given ``minAge`` interval.
- are considered stale after a given ``maxAge`` interval.
- are refreshed in a background thread, to prevent delaying the application.
Create ``ResolverGroupGenerator``, which keeps track of multiple resolvers (one per argument map).
- it creates new GroupGenerators when appropriate.
- it closes GroupGenerators it no longer needs.
- it combines the GroupGenerator resolution from each of the instantiated generators.
The JMX collector is now being controlled by the ``ResolverGroupGenerator``, so it is prepared for asynchronous, dynamic resolvers.
The other resolvers already did the right thing.
> Async resolver

- collectors/http/src/main/java/com/groupon/lex/metrics/collector/httpget/UrlGetCollector.java
- collectors/http/src/test/java/com/groupon/lex/metrics/collector/httpget/UrlPatternTest.java
apache-nio HTTP client appears to occasionally shut down.  No idea why.
As a work-around, restart the HTTP client if it appears to have stopped.
> Url collector reactor workaround

- impl/src/main/java/com/groupon/lex/metrics/PushMetricRegistryInstance.java
Detected a bug when taking down my history server, causing my collection cycle to stop.
It likely also present with the file-based history, I just never have that throw an exception so far.
> Catch exceptions that may be returned by CollectHistory.add.

- history/src/main/java/com/groupon/lex/metrics/history/TSData.java
- history/src/main/java/com/groupon/lex/metrics/history/xdr/MmapReadonlyTSDataFile.java
- history/src/main/java/com/groupon/lex/metrics/history/xdr/TSDataFileChain.java
- history/src/main/java/com/groupon/lex/metrics/history/xdr/UnmappedReadonlyTSDataFile.java
- history/src/main/java/com/groupon/lex/metrics/history/xdr/WriteableTSDataFile.java
- history/src/main/java/com/groupon/lex/metrics/history/xdr/support/FileIterator.java
- history/src/main/java/com/groupon/lex/metrics/history/xdr/support/FileTimeSeriesCollection.java
- history/src/main/java/com/groupon/lex/metrics/history/xdr/support/MultiFileIterator.java
- history/src/test/java/com/groupon/lex/metrics/history/xdr/TSDataTest.java
- impl/src/main/java/com/groupon/lex/metrics/timeseries/BackRefTimeSeriesCollection.java
- impl/src/main/java/com/groupon/lex/metrics/timeseries/MutableTimeSeriesCollection.java
- intf/src/main/java/com/groupon/lex/metrics/timeseries/AbstractTimeSeriesCollection.java
- intf/src/main/java/com/groupon/lex/metrics/timeseries/TimeSeriesCollection.java
- remote_history/src/main/java/com/groupon/monsoon/remote/history/RpcTimeSeriesCollection.java
Allow history module to deal with out-of-order and duplicate history entries.
- Out-of-order entries are reordered.
- Collections with the same timestamp are merged (overwriting groups in undefined order if need be).
- Files intersecting their time range are merged.
> History dups

- impl/src/main/java/com/groupon/lex/metrics/PushMetricRegistryInstance.java
- impl/src/main/java/com/groupon/lex/metrics/history/HistoryContext.java
- impl/src/main/java/com/groupon/lex/metrics/timeseries/AbstractTSCPair.java
- impl/src/main/java/com/groupon/lex/metrics/timeseries/ImmutableTimeSeriesCollectionPair.java
- impl/src/main/java/com/groupon/lex/metrics/timeseries/InterpolatedTSC.java
- impl/src/main/java/com/groupon/lex/metrics/timeseries/TimeSeriesCollectionPair.java
- impl/src/main/java/com/groupon/lex/metrics/timeseries/TimeSeriesCollectionPairInstance.java
- impl/src/main/java/com/groupon/lex/metrics/timeseries/expression/RateExpression.java
- impl/src/test/java/com/groupon/lex/metrics/config/impl/MatchTransformerImplTest.java
- impl/src/test/java/com/groupon/lex/metrics/config/parser/AbstractExpressionTest.java
- impl/src/test/java/com/groupon/lex/metrics/config/parser/FunctionTest.java
- impl/src/test/java/com/groupon/lex/metrics/timeseries/AbstractTSCPairTest.java
- impl/src/test/java/com/groupon/lex/metrics/timeseries/TimeSeriesCollectionPairInstanceTest.java
- impl/src/test/java/com/groupon/lex/metrics/timeseries/expression/ArithmaticFloatTest.java
- impl/src/test/java/com/groupon/lex/metrics/timeseries/expression/ArithmaticIntegralTest.java
- impl/src/test/java/com/groupon/lex/metrics/timeseries/expression/BooleanExprTest.java
- impl/src/test/java/com/groupon/lex/metrics/timeseries/expression/MetricSelectorTest.java
- impl/src/test/java/com/groupon/lex/metrics/timeseries/expression/MutableContextTest.java
- impl/src/test/java/com/groupon/lex/metrics/timeseries/expression/SimpleContextTest.java
- impl/src/test/java/com/groupon/lex/metrics/timeseries/expression/StringExprTest.java
- impl/src/test/java/com/groupon/lex/metrics/transformers/IdentifierNameResolverTest.java
- impl/src/test/java/com/groupon/lex/metrics/transformers/NameResolverCombineTest.java
- lib/src/main/java/com/groupon/lex/metrics/lib/LazyMap.java
- lib/src/test/java/com/groupon/lex/metrics/lib/LazyMapTest.java
Allow for interpolating metric values.
Used by rate() function to get correct rates.
With some modification to the history context resolution, this can also be used to fill in missing metric values and do actual stepping (i.e. make the stepSize parameter a fixed size delta, rather than a at-least-next distance).
https://github.com/groupon/monsoon/pull/39 takes care of the history module, which is needed if this diff is used in combination with a history server accepting data from multiple monsoon instances.
> Interpolation

- impl/src/main/java/com/groupon/lex/metrics/timeseries/InterpolatedTSC.java
Makes *bool interpolation* follow the formula ``(double)past_bool * past_weight + (double)future_bool * future_weight`` instead of *repeating last value*.
> Interpolate bool better -- last value doesn't look right after all.

- impl/src/main/java/com/groupon/lex/metrics/history/CollectHistory.java
Makes sure the entire LOOK_BACK and LOOK_FORWARD durations are included when performing a stepped stream traversal.
> Include LOOK_{BACK,FORWARD} in data used by stepSize-based streaming.

- lib/pom.xml
- lib/src/main/java/com/groupon/lex/metrics/lib/BytesParser.java
- lib/src/test/java/com/groupon/lex/metrics/lib/BytesParserTest.java
- rhist_server/src/main/java/com/groupon/monsoon/remote/history/server/RhistMain.java
Adds ``-s`` argument to history server.
Example:
java -jar monsoon-rhist-server.jar -s 128G /path/to/history
will clamp the history dir size to 128G.
> Add history-size option for history server.

- impl/src/main/java/com/groupon/lex/metrics/history/CollectHistory.java
This makes a query like:
http://localhost:9998/api/monsoon/eval?expr%3Atest=sum%28w%20up%29&begin=0
run in 1:30 minutes instead of 2:10 minutes.
> Buffer the interpolated Collections for Context/Evaluation stream.

- impl/src/main/java/com/groupon/lex/metrics/api/endpoints/StreamingJsonListEntity.java
- lib/src/main/java/com/groupon/lex/metrics/lib/BufferedIterator.java
This makes them safe to be called from any ForkJoinPool, which is rather nice.
The original problem was that the BufferedIterator would block
(waiting for a wakeup), while the original thread already consumed all workers
in the threadpool.
As a consequence, the threadpool was exhausted and the job that would fulfill
the wakeup condition never started.
By calling the Wakeup blocking operation using ForkJoinPool.managedBlock(),
the pool will create new threads if required.
> Prevent deadlock when BufferedIterators are nested on the stack.

- impl/src/main/java/com/groupon/lex/metrics/timeseries/TimeSeriesMetricAggregate.java
Change abstract aggregate implementation:
- simpler code (okay, as simple as aggregation logic can be)
- same performance as old code (before adding parallelstream, see below)
- case for interval-based and no-interval are very similar
- in the process, fix a bug with nested aggregates not working properly (no idea what the cause was, but I'm going to be happy none-the-less)
- use *parallelstream* for interval-based aggregates; it seems to not mess up the ForkJoinPool, so that is promising :)
> Simpler aggregate

- history/src/main/java/com/groupon/lex/metrics/history/v2/ExportMap.java
- history/src/main/java/com/groupon/lex/metrics/history/v2/tables/ToXdrTables.java
- history/src/main/java/com/groupon/lex/metrics/history/xdr/support/FJPTaskExecutor.java
- history/src/main/java/com/groupon/lex/metrics/history/xdr/support/reader/FileChannelReader.java
- history/src/main/java/com/groupon/lex/metrics/history/xdr/support/writer/FileChannelWriter.java
Makes creating table files a lot faster.
Also, compression on the temp files seems to help with speed (reduced IO load?), so enable that.
> Parallellize table file creation.

- history/src/main/java/com/groupon/lex/metrics/history/v2/tables/ToXdrTables.java
When using ``groups`` in multi-threaded code, make sure it is safe to use that way.
> Use concurrent map when doing concurrent ops.

- history/src/main/java/com/groupon/lex/metrics/history/v2/Compression.java
- history/src/main/java/com/groupon/lex/metrics/history/v2/list/ReadWriteState.java
- history/src/main/java/com/groupon/lex/metrics/history/v2/tables/ToXdrTables.java
- history/src/main/java/com/groupon/lex/metrics/history/xdr/support/TmpFile.java
- history/src/main/java/com/groupon/lex/metrics/history/xdr/support/reader/LzoReader.java
- history/src/main/java/com/groupon/lex/metrics/history/xdr/support/writer/AbstractSegmentWriter.java
- history/src/main/java/com/groupon/lex/metrics/history/xdr/support/writer/LzoWriter.java
- history/src/test/java/com/groupon/lex/metrics/history/xdr/DirCollectHistoryTest.java
- history/src/test/java/com/groupon/lex/metrics/history/xdr/support/reader/FileChannelSegmentReaderTest.java
- history/src/test/java/com/groupon/lex/metrics/history/xdr/support/writer/AbstractSegmentWriterTest.java
Allow for compressions that have a high-compression method (ex: LZO-1X) to use high compression on table files.
> High compression

- history/src/main/java/com/groupon/lex/metrics/history/v2/Compression.java
- history/src/main/java/com/groupon/lex/metrics/history/xdr/TSDataScanDir.java
- Read files in directory in parallel (speeds up initialization of DirCollectHistory).
- Use LZO compression for list files (supposedly a bit faster than Gzip).
> Minor optimizations

- history/src/main/java/com/groupon/lex/metrics/history/v2/tables/ToXdrTables.java
- history/src/main/java/com/groupon/lex/metrics/history/xdr/support/Monitor.java
Synchronization around writer access locked down the fork join pool
and caused intermittent hangs (I noticed one of 10+ seconds).
So instead of synchronizing, use a monitor that executes the write
tasks on the fork join pool.
Note that the write tasks usually involve compression, so they're
computationally expensive at least.
> Unblock the fork join pool.

- history/src/main/java/com/groupon/lex/metrics/history/v2/Compression.java
Not sure what's going on, but until I figure it out, use gzip, which is
known to work.
> Use gzip, as I saw some failing checksums with LZO 1X-999.

- history/src/main/java/com/groupon/lex/metrics/history/v2/tables/ToXdrTables.java
- intf/src/main/java/com/groupon/lex/metrics/timeseries/TimeSeriesValue.java
The race condition caused it to sometimes drop a group, due to lacking
synchronization on the intermediate arraylist during encoding.
> Fix race condition in ToXdrTables.

- lib/src/main/java/com/groupon/lex/metrics/lib/sequence/SortedObjectSequence.java
- lib/src/test/java/com/groupon/lex/metrics/lib/BufferedIteratorTest.java
- Increase timeouts for ``BufferedIterator`` tests, as they sometimes timed out on travis-ci.
- Remove stderr printing from ``SortedObjectSequence``.
> Misc fixes

- collectors/collectd/src/main/java/com/groupon/lex/metrics/collector/collectd/CollectdPushCollector.java
- collectors/collectd/src/test/java/com/groupon/lex/metrics/collector/collectd/CollectdPushCollectorTest.java
- collectors/http/src/main/java/com/groupon/lex/metrics/collector/httpget/UrlGetCollector.java
- collectors/http/src/test/java/com/groupon/lex/metrics/collector/httpget/UrlGetCollectorTest.java
- collectors/http/src/test/java/com/groupon/lex/metrics/collector/httpget/UrlJsonCollectorTest.java
- collectors/jmx/src/main/java/com/groupon/lex/metrics/jmx/JmxBuilder.java
- collectors/jmx/src/main/java/com/groupon/lex/metrics/jmx/JmxClient.java
- collectors/jmx/src/main/java/com/groupon/lex/metrics/jmx/MBeanGroup.java
- collectors/jmx/src/main/java/com/groupon/lex/metrics/jmx/MetricListener.java
- collectors/jmx/src/test/java/com/groupon/lex/metrics/jmx/JmxClient_remoteTest.java
- collectors/jmx/src/test/java/com/groupon/lex/metrics/jmx/MBeanGroupTest.java
- collectors/jmx/src/test/java/com/groupon/lex/metrics/jmx/MetricListenerTest.java
- impl/src/main/java/com/groupon/lex/metrics/MetricRegistryInstance.java
- impl/src/test/java/com/groupon/lex/metrics/MetricRegistryInstanceTest.java
- impl/src/test/java/com/groupon/lex/metrics/config/JmxListenerMonitorTest.java
- impl/src/test/java/com/groupon/lex/metrics/config/parser/ReplayCollector.java
- intf/src/main/java/com/groupon/lex/metrics/GroupGenerator.java
- intf/src/main/java/com/groupon/lex/metrics/MetricRegistry.java
- intf/src/main/java/com/groupon/lex/metrics/ResolverGroupGenerator.java
- intf/src/main/java/com/groupon/lex/metrics/SynchronousGroupGenerator.java
- lib/src/main/java/com/groupon/lex/metrics/lib/GCCloseable.java
- Make ``GroupGenerator``s asynchronous.
- To keep easy creation of collectors, the ``SynchronousGroupGenerator`` is an abstract base class for those cases where asynchronous operation is not needed.
- Monsoon currently uses up to 1k threads for IO.
> Async collector

- history/src/main/java/com/groupon/lex/metrics/history/xdr/DirCollectHistory.java
Basically, if you have a lot of disk space, collect a lot of data before rolling over the file.
- Keeps number of files down.
- Optimized table files don't mind being really large, in fact they may work better.
> Implement heuristic for automatic file size in DirCollectHistory.

- collectors/tcp/src/main/java/com/github/groupon/monsoon/tcp/TcpBuilder.java
Makes it possible to actually parse the config for  a TCP collector.
> Fix tcp collector builder, so it can be parsed.

- CHANGELOG.md
- history/src/main/java/com/groupon/lex/metrics/history/v2/list/ReadOnlyState.java
The original code for decoding a library created a chain of
``SegmentReader.combine()`` calls. For large list files, decoding
the built chain could trigger a stack overflow error.
Instead of building a chain of ``combine()`` calls, move the loop
inside a (custom) ``SegmentReader``, eliminating the stack based
recursion.
> Fix stack overflow for reading large list files.

- impl-intf/src/main/java/com/groupon/lex/metrics/history/CollectHistory.java
- impl-intf/src/main/java/com/groupon/lex/metrics/timeseries/AbstractTSCPair.java
- impl/src/main/java/com/groupon/lex/metrics/timeseries/ChainingTSCPair.java
- impl/src/main/java/com/groupon/lex/metrics/timeseries/TimeSeriesCollectionPairInstance.java
Back the TSC pair (that is used for scraping) with the history, instead of copying the history into it.
> History backed tscpair

- expr/src/main/java/com/groupon/lex/metrics/MetricMatcher.java
- expr/src/main/java/com/groupon/lex/metrics/timeseries/InterpolatedTSC.java
- expr/src/test/java/com/groupon/lex/metrics/timeseries/InterpolatedTSCTest.java
- history/src/main/java/com/groupon/lex/metrics/history/v0/xdr/ToXdr.java
- history/src/main/java/com/groupon/lex/metrics/history/v2/list/ListTSC.java
- history/src/main/java/com/groupon/lex/metrics/history/v2/list/ReadWriteState.java
- history/src/main/java/com/groupon/lex/metrics/history/v2/tables/RTFTimeSeriesCollection.java
- history/src/main/java/com/groupon/lex/metrics/history/v2/xdr/Util.java
- impl/src/main/java/com/groupon/lex/metrics/config/impl/MatchTransformerImpl.java
- impl/src/main/java/com/groupon/lex/metrics/misc/MonitorMonitor.java
- impl/src/main/java/com/groupon/lex/metrics/timeseries/ChainingTSCPair.java
- impl/src/main/java/com/groupon/lex/metrics/timeseries/MutableTimeSeriesCollection.java
- impl/src/test/java/com/groupon/lex/metrics/timeseries/MutableTimeSeriesCollectionTest.java
- intf/src/main/java/com/groupon/lex/metrics/timeseries/EmptyTimeSeriesCollection.java
- intf/src/main/java/com/groupon/lex/metrics/timeseries/SimpleTimeSeriesCollection.java
- intf/src/main/java/com/groupon/lex/metrics/timeseries/TimeSeriesCollection.java
Allows dynamic TimeSeriesCollection instances to fault in only the paths/groups that are requested, by applying a filter prior to faulting in.
> Predicate based access to TimeSeriesCollection

- file_convert/src/main/java/com/groupon/lex/metrics/FileConvert.java
- history/src/main/java/com/groupon/lex/metrics/history/v2/tables/ToXdrTables.java
- history/src/main/java/com/groupon/lex/metrics/history/xdr/DirCollectHistory.java
- history/src/main/java/com/groupon/lex/metrics/history/xdr/TSDataFileChain.java
Makes the file converter waste less time with decoding and encoding data, by bypassing the record-based file entirely.
> Batch operations

- expr/src/main/antlr4/com/groupon/lex/metrics/timeseries/parser/PathMatcherGrammar.g4
- expr/src/main/antlr4/com/groupon/lex/metrics/timeseries/parser/PathMatcherLexer.g4
- expr/src/main/antlr4/imports/ExprBnf.g4
- expr/src/main/java/com/groupon/lex/metrics/PathMatcher.java
- expr/src/main/java/com/groupon/lex/metrics/expression/GroupExpression.java
- expr/src/main/java/com/groupon/lex/metrics/expression/IdentifierGroupExpression.java
- expr/src/main/java/com/groupon/lex/metrics/expression/LiteralGroupExpression.java
- expr/src/main/java/com/groupon/lex/metrics/timeseries/TimeSeriesMetricAggregate.java
- expr/src/main/java/com/groupon/lex/metrics/timeseries/TimeSeriesMetricExpression.java
- expr/src/main/java/com/groupon/lex/metrics/timeseries/TimeSeriesMetricFilter.java
- expr/src/main/java/com/groupon/lex/metrics/timeseries/expression/IdentifierMetricSelector.java
- expr/src/main/java/com/groupon/lex/metrics/timeseries/expression/MetricSelector.java
- expr/src/main/java/com/groupon/lex/metrics/timeseries/expression/NameExpression.java
- expr/src/main/java/com/groupon/lex/metrics/timeseries/expression/TimeSeriesMetricSelector.java
- expr/src/main/java/com/groupon/lex/metrics/transformers/IdentifierNameResolver.java
- expr/src/main/java/com/groupon/lex/metrics/transformers/LiteralNameResolver.java
- expr/src/main/java/com/groupon/lex/metrics/transformers/NameResolver.java
- expr/src/test/java/com/groupon/lex/metrics/expression/GroupExpressionTest.java
- expr/src/test/java/com/groupon/lex/metrics/timeseries/ExprNameFilterTest.java
Allows expressions to generate sets of paths that are needed for the expression to be resolved.
> Path matcher parsing

- exporter/src/main/java/com/groupon/lex/metrics/Exporter.java
- history/src/test/java/com/groupon/lex/metrics/history/xdr/DirCollectHistoryTest.java
- impl-intf/src/main/java/com/groupon/lex/metrics/history/CollectHistory.java
- lib/src/main/java/com/groupon/lex/metrics/lib/BufferedIterator.java
- lib/src/test/java/com/groupon/lex/metrics/lib/BufferedIteratorTest.java
The temptation is too large to just throw them in along a stream/iteration,
to split a computation over multiple threads (or deal with IO). But the
downside is that this will lead to deadlock scenarios, where all threads are
used for BufferedIterators, which are all waiting for other BufferedIterators
to do their work. And of course the latter can't, because they're waiting for
threads...
> Remove iterator/stream wrappers from BufferedIterator.

- extra/influx/src/main/java/com/github/groupon/monsoon/history/influx/InfluxHistory.java
- history/src/main/java/com/groupon/lex/metrics/history/v2/tables/RTFTimeSeriesCollection.java
- history/src/main/java/com/groupon/lex/metrics/history/v2/tables/RTFTimeSeriesValue.java
- impl-intf/src/main/java/com/groupon/lex/metrics/history/CollectHistory.java
- remote_history/src/test/java/com/groupon/monsoon/remote/history/ClientServerTest.java
Parallelize decoding operations for faster bulk decoding.
While here, create ``CollectHistory.addAll(Iterator)`` method as alternative insertion method.
> Use faster bulk decoding logic.

- extra/influx-copy/src/main/java/com/github/groupon/monsoon/history/influx/FileConvert.java
- extra/influx/src/main/java/com/github/groupon/monsoon/history/influx/InfluxHistory.java
Telegraf cannot handle the database-exist test, so allow for that to be
suppressed.
Telegraf does not handle lines longer than 64k. So we work around this by
testing if a line is shorter than 32k (gives plenty of buffer).
> Work around telegraf limitations.

- pom.xml
Maven will run all tests in a single forked VM by default. This can be problematic if there are a lot of tests or some very memory-hungry ones. We can fork more test VM by setting `<fork>1.5C</fork>`.
=====================
If there are any inappropriate modifications in this PR, please give me a reply and I will change them.
> Improve performance in the Test phase
