README.md

Adding a little green thingy that says everything is okay.

Test the CI integration in the readme.

---

doc/prometheus/README.md

Updating documentation: Prometheus Invocation to include config file.

Updated Prometheus Invocation

---

http_get_collector/pom.xml
http_get_collector/src/main/antlr4/com/groupon/lex/metrics/collector/httpget/grammar/CollectdTags.g4
http_get_collector/src/main/java/com/groupon/lex/metrics/collector/httpget/CollectdPushCollector.java
http_get_collector/src/main/java/com/groupon/lex/metrics/collector/httpget/grammar/CollectdTags.java
http_get_collector/src/test/java/com/groupon/lex/metrics/collector/httpget/CollectdPushCollector_CollectdKeyTest.java
http_get_collector/src/test/java/com/groupon/lex/metrics/collector/httpget/CollectdPushCollector_CollectdMessageTest.java

This implements the tag handling for *collectd*.
Note that the tagging in *collectd* is a convention.  Parser is designed to cover most cases, but I'm sure I missed some, in which case example in the bug report would be nice. :)

Collectd tags

---

exporter/pom.xml
exporter/src/main/java/com/groupon/lex/metrics/Exporter.java
exporter/src/main/java/com/groupon/lex/metrics/json/Json.java
exporter/src/main/java/com/groupon/lex/metrics/json/JsonGroupName.java
exporter/src/main/java/com/groupon/lex/metrics/json/JsonHistogramKey.java
exporter/src/main/java/com/groupon/lex/metrics/json/JsonNamedMetric.java
exporter/src/main/java/com/groupon/lex/metrics/json/JsonTags.java
exporter/src/main/java/com/groupon/lex/metrics/json/JsonTimeSeriesValue.java
pom.xml

It's currently not very intelligent, in that it'll convert the entire
history into json.
Json is streamed to stdout.

Create a json history exporter.

---

impl/src/main/java/com/groupon/lex/metrics/PipelineBuilder.java

Meaning between ``epr`` and ``api`` variables was mismanaged.
Also, ensure ``close()`` methods won't overwrite the exception cause during cleanup in catch block.

Fixes for when builtin api server is not used.

---

impl/src/main/java/com/groupon/lex/metrics/timeseries/InterpolatedTSC.java

If underlying collection throws an exception, interpolated TimeSeriesCollection will not be modified.

Make interpolated TSC modifications have strong exception guarantee.

---

api_bin/pom.xml
api_bin/src/main/java/com/github/groupon/monsoon/api/bin/ApiBin.java
api_bin/src/main/java/com/github/groupon/monsoon/api/bin/ApiServerSocketOptionHandler.java
api_bin/src/main/java/com/github/groupon/monsoon/api/bin/RHistClientSocketOptionHandler.java
api_server/src/main/java/com/groupon/lex/metrics/api/ApiServer.java
lib/src/main/java/com/groupon/lex/metrics/lib/HostnamePort.java
lib/src/main/java/com/groupon/lex/metrics/lib/InetAddressOptionHandler.java
lib/src/main/java/com/groupon/lex/metrics/lib/ManyInetAddressOptionHandler.java
pom.xml

A standalone API webserver.
It can only evaluate queries, using a remote history.

Create API server that only listens.

---

lib/src/main/java/com/groupon/lex/metrics/lib/BufferedIterator.java
remote_history/src/main/java/com/groupon/monsoon/remote/history/AbstractServer.java
remote_history/src/main/java/com/groupon/monsoon/remote/history/Client.java
remote_history/src/test/java/com/groupon/monsoon/remote/history/ClientServerTest.java

Make RPC History client inform ForkJoinPool of blocking.
Add timed wait to BufferedIterator, so RPC History server can control the timeouts better.
Allow RPC History server to return empty results and make client deal with that appropriately.

RPC async friendliness.

---

lib/src/main/java/com/groupon/lex/metrics/lib/BufferedIterator.java

Reading the hasNext() property of the underlying iterator in the constructor
of the buffered iterator, causes the constructor to block until the underlying
iterator produces its first element.  This can take a long time and caused
RPC timeouts if the underlying iterator wasn't ready in 30 seconds.

Fix rpc timeout: don't read iterator in buffered iterator constructor.

---

history/src/main/java/com/groupon/lex/metrics/history/v2/xdr/Util.java
lib/src/main/java/com/groupon/lex/metrics/lib/sequence/CachingObjectSequence.java
lib/src/main/java/com/groupon/lex/metrics/lib/sequence/ConcatObjectSequence.java
lib/src/main/java/com/groupon/lex/metrics/lib/sequence/EmptyObjectSequence.java
lib/src/main/java/com/groupon/lex/metrics/lib/sequence/ForwardSequence.java
lib/src/main/java/com/groupon/lex/metrics/lib/sequence/IntObjectSequence.java
lib/src/main/java/com/groupon/lex/metrics/lib/sequence/MappingObjectSequence.java
lib/src/main/java/com/groupon/lex/metrics/lib/sequence/ObjectSequence.java
lib/src/main/java/com/groupon/lex/metrics/lib/sequence/ReverseSequence.java
lib/src/main/java/com/groupon/lex/metrics/lib/sequence/Sequence.java
lib/src/main/java/com/groupon/lex/metrics/lib/sequence/SortedObjectSequence.java
lib/src/test/java/com/groupon/lex/metrics/lib/sequence/EmptyObjectSequenceTest.java
lib/src/test/java/com/groupon/lex/metrics/lib/sequence/SortedObjectSequenceTest.java

Makes fixing sequences something that is done as the stream progresses, rather than an upfront activity.

Perform lazy sorting and merging where possible.

---

file_convert/src/main/java/com/groupon/lex/metrics/FileConvert.java
history/src/main/java/com/groupon/lex/metrics/history/v2/tables/ToXdrTables.java
history/src/main/java/com/groupon/lex/metrics/history/xdr/TSDataFileChain.java
history/src/main/java/com/groupon/lex/metrics/history/xdr/TSDataOptimizerTask.java

- Isolate file creation subtasks by running in its own fork-join-pool.
- Use temporary file until all data is completed, then install by copy operation.
- Use strong thread during installing of optimized file.

Cleaner implementation of background optimization.

---

history/src/main/java/com/groupon/lex/metrics/history/xdr/TSDataOptimizerTask.java

- Fixes outstanding task handling (both the registration and deregistration, plus making all that thread-safe).
- Changes to a single ``task`` executor, so that optimization won't happen in parallel (it's heavy on memory) and that multiple optimizations can be queued.

Fix handling of OUTSTANDING optimizer tasks.

---

history/src/main/java/com/groupon/lex/metrics/history/v2/tables/ToXdrTables.java
history/src/main/java/com/groupon/lex/metrics/history/xdr/DirCollectHistory.java
history/src/main/java/com/groupon/lex/metrics/history/xdr/TSDataFileChain.java
history/src/test/java/com/groupon/lex/metrics/history/xdr/TSDataFileChainTest.java
rhist_server/src/main/java/com/groupon/monsoon/remote/history/server/RhistMain.java

Implement functionality to optimize existing files in history.

Optimize old files

---

history/src/main/java/com/groupon/lex/metrics/history/xdr/TSDataFileChain.java
history/src/main/java/com/groupon/lex/metrics/history/xdr/TSDataOptimizerTask.java

Isolates the optimizer thread from file removal by the history.

Make background selection and optimization simpler.

---

history/src/main/java/com/groupon/lex/metrics/history/xdr/UnmappedReadonlyTSDataFile.java

Make the v0.x and v1.x files less of a strain on the GC/heap. Parallel Mark-Sweep GC is really bad at dealing with SoftReferences, if they exceed memory, so we make the old file sequence share-only (i.e. GC-ed as soon as possible).

Change how sequence in old file works exactly.

---

history/src/main/java/com/groupon/lex/metrics/history/xdr/UnmappedReadonlyTSDataFile.java

Turns out pure soft references causes parallel GC to not deal properly. Use SegmentReader to share (but not cache) the sequence instead.

Use segment reader to reduce memory pressure.

---

collectors/jmx/src/main/java/com/groupon/lex/metrics/jmx/MBeanGroupInstance.java
collectors/jmx/src/main/java/com/groupon/lex/metrics/jmx/MetricListenerInstance.java
intf/src/main/java/com/groupon/lex/metrics/AttributeConverter.java

Because JMX scraping is excessively noisy.

Quieter jmx

---

CHANGELOG.md
collectors/pom.xml
collectors/tcp/pom.xml
collectors/tcp/src/main/java/com/github/groupon/monsoon/tcp/TcpBuilder.java
collectors/tcp/src/main/java/com/github/groupon/monsoon/tcp/TcpCollector.java
collectors/tcp/src/test/java/com/github/groupon/monsoon/tcp/TcpBuilderTest.java
collectors/tcp/src/test/java/com/github/groupon/monsoon/tcp/TcpCollectorTest.java
doc/collectors/index.md
doc/collectors/tcp.md
impl/pom.xml
impl/src/main/java/com/groupon/lex/metrics/config/Configuration.java
intf/src/main/java/com/groupon/lex/metrics/resolver/NamedResolverMap.java

Implement a simple TCP collector.

---

impl/src/main/java/com/groupon/lex/metrics/PushProcessorPipeline.java

Turns out Java's ScheduledExecutorService _silently_ stops a scheduled
task if it lets an exception or error escape.
To deal with this:
- Catch all exceptions and errors.
- Log those exceptions and errors.
- Don't let those exceptions and errors escape any further.
Note the pull-processors should keep propagating exceptions and errors
as usual.

Push processor stops completely and silently.

---

doc/collectors/tcp.md

Fixed a usage typo in Documentation.

Update to tcp collector documentation 

---

intf/src/main/java/com/groupon/lex/metrics/BasicPath.java
intf/src/main/java/com/groupon/lex/metrics/MetricName.java
intf/src/main/java/com/groupon/lex/metrics/SimpleGroupPath.java
intf/src/main/java/com/groupon/lex/metrics/Tags.java

Use a few more arrays in place of objects, to reduce memory overhead.
Also refactor path-based logic into a shared base class.

Minor refactorings and slightly more efficient storage.

---

CHANGELOG.md
api_server/src/main/frontend/app/eval/evaluation.service.ts
impl/src/main/java/com/groupon/lex/metrics/api/endpoints/ExprEval.java

Adds a flag to the metrics endpoint, to emit only numeric values.

Allow for numeric-only values to be emitted.

---

expr/src/main/java/com/groupon/lex/metrics/timeseries/TagMatchingClause.java
expr/src/main/java/com/groupon/lex/metrics/timeseries/TimeSeriesCollectionPair.java
expr/src/main/java/com/groupon/lex/metrics/timeseries/expression/AbstractBiExpression.java
expr/src/main/java/com/groupon/lex/metrics/timeseries/expression/AbstractBiPredicate.java
expr/src/main/java/com/groupon/lex/metrics/timeseries/expression/RateExpression.java
expr/src/main/java/com/groupon/lex/metrics/timeseries/expression/StrConcatExpression.java
expr/src/main/java/com/groupon/lex/metrics/timeseries/expression/UtilX.java
expr/src/test/java/com/groupon/lex/metrics/PathMatcherTest.java
expr/src/test/java/com/groupon/lex/metrics/timeseries/ImmutableTimeSeriesCollectionPairTest.java
expr/src/test/java/com/groupon/lex/metrics/timeseries/TimeSeriesCollectionPairTest.java
expr/src/test/java/com/groupon/lex/metrics/timeseries/expression/ArithmaticHistogramTest.java
expr/src/test/java/com/groupon/lex/metrics/timeseries/expression/Checks.java
expr/src/test/java/com/groupon/lex/metrics/timeseries/expression/EqualityPredicateTest.java
expr/src/test/java/com/groupon/lex/metrics/timeseries/expression/InequalityPredicateTest.java
expr/src/test/java/com/groupon/lex/metrics/timeseries/expression/PercentileAggregateExpressionTest.java
expr/src/test/java/com/groupon/lex/metrics/timeseries/expression/RateExpressionTest.java
impl/src/test/java/com/groupon/lex/metrics/config/parser/ExpressionTest.java
intf/src/main/java/com/groupon/lex/metrics/Histogram.java
intf/src/test/java/com/groupon/lex/metrics/HistogramTest.java

Improve expression coverage. Also fix some bugs while here.

Expr coverage

---

file_convert/src/main/java/com/groupon/lex/metrics/FileConvert.java
history/src/main/java/com/groupon/lex/metrics/history/AbstractCollectHistory.java
history/src/main/java/com/groupon/lex/metrics/history/TSData.java
history/src/main/java/com/groupon/lex/metrics/history/v2/Compression.java
history/src/main/java/com/groupon/lex/metrics/history/xdr/TSDataFileChain.java
history/src/main/java/com/groupon/lex/metrics/history/xdr/TSDataOptimizerTask.java
history/src/main/java/com/groupon/lex/metrics/history/xdr/support/SequenceTSData.java
history/src/test/java/com/groupon/lex/metrics/history/xdr/TSDataTest.java
rhist_server/src/main/java/com/groupon/monsoon/remote/history/server/RhistMain.java

Allow compression to be manipulated at runtime and from the command line.

Set compression

---

history/src/main/java/com/groupon/lex/metrics/history/v2/tables/RTFMetricTable.java

Discovered there were a lot of unneeded tables for history-decoded metric values during conversion. Most values don't require all types, so it makes sense to use an empty array when a type is completely absent.

Reduce memory usage for metric tables, by optimizing away empty table values.

---

history/src/main/java/com/groupon/lex/metrics/history/xdr/support/TmpFile.java

While here, make it thread-safe.

Fix: TmpFile erroneously did not allow multiple iterations.

---

history/src/main/java/com/groupon/lex/metrics/history/xdr/TSDataOptimizerTask.java

The thread pool used normal threads, instead of daemon threads, causing the application to stay alive after the main thread exited.
Make them daemon threads instead.

fix: TSDataOptimizerTask kept application alive.

---

collectors/jmx/src/main/java/com/groupon/lex/metrics/jmx/JmxClient.java
collectors/jmx/src/test/java/com/groupon/lex/metrics/jmx/JmxClient_remoteTest.java

I wasn't sure if this was properly tested. Looks like it wasn't. Anyways, handled correctly.

Test if connection breakage is handled right (it is!)

---

extra/influx-copy/pom.xml
extra/influx-copy/src/main/java/com/github/groupon/monsoon/history/influx/FileConvert.java
extra/influx/src/main/java/com/github/groupon/monsoon/history/influx/InfluxHistory.java
extra/pom.xml
history/src/main/java/com/groupon/lex/metrics/history/v2/tables/RTFTimeSeriesCollection.java
history/src/main/java/com/groupon/lex/metrics/history/v2/tables/RTFTimeSeriesValue.java

Simply utility that (very slowly) copies data from monsoon to influx. Mostly POC code.

Copy to influx
